### PR TITLE
preliminary skeleton of unlocked question

### PR DESCRIPTION
**Pull request by xbdell**
Adds basic layout styling to previously answered question:

screen shot 2017-11-05 at 2 21 14 pm

### CODE REVIEW

**Comment by xbdell** [comment]
@beakerandjake lemme know what you think

**Comment by beakerandjake** [comment]
Looks legit, maybe an HR below answer and maybe a [humanize](https://momentjs.com/docs/#/durations/humanize/) for the Time to Complete in case it starts getting into weeks.

check public-view.controller.js for a humanize 


```
    // Generate a human readable duration between now and when the user unlocked the question. 
    calculateTimeSinceUnlock() {
        const startTime = new moment(this.question.timeUnlocked);
        const diff = moment().diff(startTime);
        this.duration = moment.duration(diff).humanize();
    }
```

**Comment by beakerandjake** [comment]
merge whenever dude

**Comment by xbdell** [comment]
good call man, updated

**Pull request merged**
